const SC = {
  ADD_MESSAGE: 'SC_ADD_MESSAGE',
  ADD_CHANNEL: 'SC_ADD_CHANNEL',
  INIT: 'SC_INIT',
  SIGN_IN: 'SC_SIGN_IN',
  JOIN_TO_CHANNEL: 'SC_JOIN_TO_CHANNEL',
};

const CS = {
  ADD_MESSAGE: 'CS_ADD_MESSAGE',
  ADD_CHANNEL: 'CS_ADD_CHANNEL',
  SIGN_IN: 'CS_SIGN_IN',
  INIT: 'CS_INIT',
  JOIN_TO_CHANNEL: 'CS_JOIN_TO_CHANNEL',
};

const A = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  REMOVE_CHANNEL: 'REMOVE_CHANNEL',
  SET_LOCAL_STATE: 'SET_LOCAL_STATE',
  SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
  INIT: 'INIT',
  INIT_USER: 'INIT_USER',
  LOG_OUT: 'LOG_OUT',
  JOIN_TO_CHANNEL: 'JOIN_TO_CHANNEL',
};

module.exports = {
  SC: SC,
  CS: CS,
  A: A,
};
